services:
    # Command to start terminal interface
    kryptopus_command_start_terminal_interface:
        class: "application/command/StartCommand"
        arguments:
            - "@container"
        tags:
            - { name: "solfege.console.command" }


