services:
    # Command to start terminal interface
    kryptopus_command_start_terminal_interface:
        class: application/command/StartCommand
        arguments:
            - "@container"
        tags:
            - { name: solfege.console.command }

    # Body registry
    kryptopus_terminal_interface_body_registry:
        class: domain/service/BodyRegistry

    # Empty body
    kryptopus_terminal_interface_body_empty:
        class: domain/body/EmptyBody
        tags:
            - { name: kryptopus.terminal_interface.body, body_id: empty }
